# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-01 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govt_agency_access',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain.Govt_Agency'),
        ),
        migrations.AlterField(
            model_name='govt_agency_access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
